# Base Settings
dataset:
  data_directory: ..\\data\\kaggle_3m\\
  data_meta_data_dir: data\\kaggle_3m\\data.csv
data_name: breast-cancer-wisconsin.data
drop_columns: ["id"]
target_name: class
test_size: 0.3
model_directory: ../models/
model_name: 

# model params

learning_rate: 0.001
evaluation_matric: 
save_model: True
optimizer: adam
batch_size: 16
epochs: 100
pin_memory: True
image_height: 256
image_width: 256
