# Base Settings
data_directory: ../data/
data_meta_data_dir: data\kaggle_3m\data.csv
data_name: breast-cancer-wisconsin.data
drop_columns: ["id"]
target_name: class
test_size: 0.3
model_directory: ../models/
model_name: 

# model params